stages:
  - name: self-test
    if: type = push
  - name: integration
    if: branch = master OR type = pull_request

env:
 global:
  - SYS=22
  - ABI="default;armeabi-v7a"
  - ADB_INSTALL_TIMEOUT=10 # minutes

_integration_job_template: &integration_job_template
  stage: integration
  cache: npm
  install:
    - nvm install 11
    - node --version
    - gem install xcodeproj
    - npm install
    - npm install -g yarn
    - npm install -g react-native-cli
  before_script:
    - integration-tests/scripts/make-project $RN_VERSION integration-tests/Setup

_android_job_template: &android_job_template
  <<: *integration_job_template
  language: generic
  dist: trusty
  before_install:
    - export ANDROID_HOME=~/android-sdk
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3 # give xvfb some time to start
    - integration-tests/scripts/setup-android-sdk
  # before_script will make project
  script:
    - integration-tests/scripts/wait-for-emulator
    - cd integration-tests/Setup
    - node_modules/.bin/flow check
    - cd android
    - npm start &
    - sleep 5
    - curl -s http://localhost:8081/index.bundle\?platform\=ios\&dev\=true\&minify\=false > /dev/null
    - ./gradlew connectedAndroidTest

_ios_job_template: &ios_job_template
  <<: *integration_job_template
  language: objective-c
  os: osx
  osx_image: xcode10.1
  xcode_project: integration-tests/Setup/ios/Setup.xcodeproj
  xcode_scheme: Setup
  xcode_destination: platform=iOS Simulator
  # before_script will make project
  script:
    - cd integration-tests/Setup
    - node_modules/.bin/flow check
    - npm start &
    - sleep 5
    - curl -s http://localhost:8081/index.bundle\?platform\=ios\&dev\=true\&minify\=false > /dev/null
    - xcodebuild test -scheme Setup -project ios/Setup.xcodeproj -quiet -UseModernBuildSystem=NO -destination 'platform=iOS Simulator,name=iPhone XS Max,OS=12.1'

matrix:
  include:
    - language: node_js
      stage: self-test
      node_js: 8
      script:
        - npm install
        - npm run lint
        - npm test

    # Integration tests for different React Native versions
    - <<: *android_job_template
      name: 'Integrate with RN 0.57.2 Android'
      env: RN_VERSION=0.57.2
    - <<: *ios_job_template
      name: 'Integrate with RN 0.57.2 iOS'
      env: RN_VERSION=0.57.2
    - <<: *android_job_template
      name: 'Integrate with RN 0.57.5 Android'
      env: RN_VERSION=0.57.5
    - <<: *ios_job_template
      name: 'Integrate with RN 0.57.5 iOS'
      env: RN_VERSION=0.57.5
    - <<: *android_job_template
      name: 'Integrate with RN 0.57.8 Android'
      env: RN_VERSION=0.57.8
    - <<: *ios_job_template
      name: 'Integrate with RN 0.57.8 iOS'
      env: RN_VERSION=0.57.8
    - <<: *android_job_template
      name: 'Integrate with RN 0.58.0 Android'
      env: RN_VERSION=0.58.0
    - <<: *ios_job_template
      name: 'Integrate with RN 0.58.0 iOS'
      env: RN_VERSION=0.58.0
    - <<: *android_job_template
      name: 'Integrate with RN 0.58.3 Android'
      env: RN_VERSION=0.58.3
    - <<: *ios_job_template
      name: 'Integrate with RN 0.58.3 iOS'
      env: RN_VERSION=0.58.3
