matrix:
  include:
    - language: node_js
      node_js: 8
      script:
        - npm install
        - npm run lint
        - npm test

    - language: android
      os: linux
      jdk: oraclejdk8
      node_js: false
      android:
        components:
          - tools
          - platform-tools
          - build-tools-23.0.3
          - android-23
      script:
        - nvm install 8
        - npm install
        - cd android
        - ls
        - ./gradlew assembleRelease

    - language: objective-c
      os: osx
      osx_image: xcode9.1
      node_js: false
      xcode_project: ios/BleClientManager/BleClientManager.xcodeproj
      script:
        - npm install
        - cd ios
        - xcodebuild -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
