stages:
  - self-test
  - integration

_integration_job_template: &integration_job_template
  stage: integration
  cache: npm
  before_install:
    - nvm install 11
    - node --version
  install:
    - gem install xcodeproj
    - npm install
    - npm install -g react-native-cli
  before_script:
    - cd examples
    - bash makeProject.sh $RN_VERSION
    - cd Setup
    - bash ../installFlow.sh

_android_job_template: &android_job_template
  <<: *integration_job_template
  language: android
  jdk: openjdk8
  android:
    components:
      - tools
      - platform-tools
      - build-tools-23.0.1
      - build-tools-26.0.3
      - build-tools-27.0.3
      - build-tools-28.0.3
      - android-25
      - android-26
      - android-27
      - android-28
      - extra-android-m2repository
      - extra-google-m2repository
      - extra-android-support
    licenses:
      - 'android-sdk-license-.+'
  script:
    - node_modules/.bin/flow check
    - cd android
    - ./gradlew assemble

_ios_job_template: &ios_job_template
  <<: *integration_job_template
  language: objective-c
  os: osx
  osx_image: xcode10.1
  xcode_project: examples/Setup/ios/Setup.xcodeproj
  xcode_scheme: Setup
  xcode_destination: platform=iOS Simulator
  script:
    - node_modules/.bin/flow check
    - RCT_NO_LAUNCH_PACKAGER=true xcodebuild -scheme Setup -project ios/Setup.xcodeproj -sdk iphonesimulator -quiet -UseModernBuildSystem=NO

matrix:
  include:
    - language: node_js
      stage: self-test
      node_js: 8
      script:
        - npm install
        - npm run lint
        - npm test

    # Integration tests for different React Native versions
    - <<: *android_job_template
      name: 'Integrate with RN 0.57.2 Android'
      env: RN_VERSION=0.57.2
    - <<: *ios_job_template
      name: 'Integrate with RN 0.57.2 iOS'
      env: RN_VERSION=0.57.2
    - <<: *android_job_template
      name: 'Integrate with RN 0.57.5 Android'
      env: RN_VERSION=0.57.5
    - <<: *ios_job_template
      name: 'Integrate with RN 0.57.5 iOS'
      env: RN_VERSION=0.57.5
    - <<: *android_job_template
      name: 'Integrate with RN 0.57.8 Android'
      env: RN_VERSION=0.57.8
    - <<: *ios_job_template
      name: 'Integrate with RN 0.57.8 iOS'
      env: RN_VERSION=0.57.8
    - <<: *android_job_template
      name: 'Integrate with RN 0.58.0 Android'
      env: RN_VERSION=0.58.0
    - <<: *ios_job_template
      name: 'Integrate with RN 0.58.0 iOS'
      env: RN_VERSION=0.58.0
    - <<: *android_job_template
      name: 'Integrate with RN 0.58.3 Android'
      env: RN_VERSION=0.58.3
    - <<: *ios_job_template
      name: 'Integrate with RN 0.58.3 iOS'
      env: RN_VERSION=0.58.3
