matrix:
  include:
    - language: node_js
      node_js: 8
      script:
        - npm install
        - npm run lint
        - npm test

    - language: android
      jdk: oraclejdk8
      node_js: false
      android:
        components:
          - tools
          - build-tools-26.0.2
          - platform-tools
          - android-25
        licenses:
          - 'android-sdk-license-.+'
      script:
        - java -version
        - cd android
        - chmod +x gradlew
        - ./gradlew assembleRelease

    - language: objective-c
      os: osx
      osx_image: xcode9.1
      node_js: false
      xcode_project: ios/BleClientManager/BleClientManager.xcodeproj
      script:
        - cd ios/BleClientManager
        - carthage build
        - xcodebuild -scheme BleClientManager -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
