stages:
  - name: self-test
    if: type = push
  - name: integration
    # FIXME re-enable
    # if: branch = master OR type = pull_request

env:
  global:
    # - FORCE_VERSION=0.10.0
    - SYS=22
    - ABI="default;armeabi-v7a"
    - ADB_INSTALL_TIMEOUT=10 # minutes

_integration_job_template: &integration_job_template
  stage: integration
  cache: npm
  install:
    - nvm install 11
    - node --version
    - gem install xcodeproj
    - npm install
    - npm install -g yarn
    - npm install -g react-native-cli
  before_script:
    - integration-tests/scripts/make-project $RN_VERSION integration-tests/Setup

_android_job_template: &android_job_template
  <<: *integration_job_template
  language: generic
  dist: trusty
  before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3 # give xvfb some time to start
    # Install android tools
    - ANDROID_TOOLS=4333796 # android-28
    - export ANDROID_HOME=~/android-sdk
    - wget -q "https://dl.google.com/android/repository/sdk-tools-linux-$ANDROID_TOOLS.zip" -O android-sdk-tools.zip
    - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
    - rm android-sdk-tools.zip
    - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
    # Silence warning.
    - mkdir -p ~/.android
    - touch ~/.android/repositories.cfg
    # Accept licenses before installing components, no need to echo y for each component
    - yes | sdkmanager --licenses
    # Platform tools
    - sdkmanager "emulator" "tools" "platform-tools" > /dev/null
    - sdkmanager --list | head -15
    # install older build tools (for emulator)
    - sdkmanager "build-tools;28.0.3" "build-tools;25.0.2" "platforms;android-28" "platforms;android-25" > /dev/null
    # Create and start emulator.
    - sdkmanager "system-images;android-$SYS;$ABI" > /dev/null
    - sdkmanager --list | head -15
    - echo no | avdmanager create avd -n test -k "system-images;android-$SYS;$ABI"
    - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window $EMU_ADDITIONAL_OPTIONS ${EMU_DEBUG} &
  # before_script will make project
  script:
    - integration-tests/scripts/wait-for-emulator
    - cd integration-tests/Setup
    - node_modules/.bin/flow check
    - cd android
    - npm start &
    - sleep 5
    - curl -s http://localhost:8081/index.bundle\?platform\=ios\&dev\=true\&minify\=false > /dev/null
    - ./gradlew connectedAndroidTest

_ios_job_template: &ios_job_template
  <<: *integration_job_template
  language: objective-c
  os: osx
  osx_image: xcode10.1
  xcode_project: integration-tests/Setup/ios/Setup.xcodeproj
  xcode_scheme: Setup
  xcode_destination: platform=iOS Simulator
  # before_script will make project
  script:
    - cd integration-tests/Setup
    - node_modules/.bin/flow check
    - npm start &
    - sleep 5
    - curl -s http://localhost:8081/index.bundle\?platform\=ios\&dev\=true\&minify\=false > /dev/null
    - xcodebuild test -scheme Setup -project ios/Setup.xcodeproj -quiet -UseModernBuildSystem=NO -destination 'platform=iOS Simulator,name=iPhone XS Max,OS=12.1'

matrix:
  include:
    - language: node_js
      stage: self-test
      node_js: 8
      script:
        - npm install
        - npm run lint
        - npm test

    # Integration tests for different React Native versions
    - <<: *android_job_template
      name: 'Integrate with RN next Android'
      env: RN_VERSION=next
    - <<: *ios_job_template
      name: 'Integrate with RN next iOS'
      env: RN_VERSION=next

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.59.1 Android'
    #   env: RN_VERSION=0.59.1
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.59.1 iOS'
    #   env: RN_VERSION=0.59.1

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.59.0 Android'
    #   env: RN_VERSION=0.59.0
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.59.0 iOS'
    #   env: RN_VERSION=0.59.0

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.58.3 Android'
    #   env: RN_VERSION=0.58.3
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.58.3 iOS'
    #   env: RN_VERSION=0.58.3

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.58.0 Android'
    #   env: RN_VERSION=0.58.0
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.58.0 iOS'
    #   env: RN_VERSION=0.58.0

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.57.8 Android'
    #   env: RN_VERSION=0.57.8
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.57.8 iOS'
    #   env: RN_VERSION=0.57.8

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.57.5 Android'
    #   env: RN_VERSION=0.57.5
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.57.5 iOS'
    #   env: RN_VERSION=0.57.5

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.57.2 Android'
    #   env: RN_VERSION=0.57.2
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.57.2 iOS'
    #   env: RN_VERSION=0.57.2

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.56.1 Android'
    #   env: RN_VERSION=0.56.1
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.56.1 iOS'
    #   env: RN_VERSION=0.56.1

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.55.4 Android'
    #   env: RN_VERSION=0.55.4
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.55.4 iOS'
    #   env: RN_VERSION=0.55.4

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.54.4 Android'
    #   env: RN_VERSION=0.54.4
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.54.4 iOS'
    #   env: RN_VERSION=0.54.4

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.53.3 Android'
    #   env: RN_VERSION=0.53.3
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.53.3 iOS'
    #   env: RN_VERSION=0.53.3

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.52.3 Android'
    #   env: RN_VERSION=0.52.3
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.52.3 iOS'
    #   env: RN_VERSION=0.52.3

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.51.1 Android'
    #   env: RN_VERSION=0.51.1
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.51.1 iOS'
    #   env: RN_VERSION=0.51.1

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.50.4 Android'
    #   env: RN_VERSION=0.50.4
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.50.4 iOS'
    #   env: RN_VERSION=0.50.4

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.49.3 Android'
    #   env: RN_VERSION=0.49.3
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.49.3 iOS'
    #   env: RN_VERSION=0.49.3

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.48.3 Android'
    #   env: RN_VERSION=0.48.3
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.48.3 iOS'
    #   env: RN_VERSION=0.48.3

    # - <<: *android_job_template
    #   name: 'Integrate with RN 0.47.2 Android'
    #   env: RN_VERSION=0.47.2
    # - <<: *ios_job_template
    #   name: 'Integrate with RN 0.47.2 iOS'
    #   env: RN_VERSION=0.47.2

  allow_failures:
    - name: 'Integrate with RN 0.55.4 Android'
    - name: 'Integrate with RN 0.55.4 iOS'
    - name: 'Integrate with RN 0.56.1 Android'
    - name: 'Integrate with RN 0.56.1 iOS'
